/**
 * Agent Builder — transcript → ClickUp PRD markdown.
 *
 * Takes a submitted session and renders it into the 10-section markdown body
 * defined in docs/prd-agent-builder.md §6. The dev reviewing the ticket can
 * walk top-to-bottom and implement.
 *
 * Kept intentionally simple: extracts each canonical question's answer from
 * the transcript and slots it into the template. Claude-authored session
 * data (proposed_name, slug, vertical_tag, capability_tag) is passed in
 * separately and populated alongside.
 */

import { CANONICAL_COUNT, getCanonicalQuestion } from "./prompts";
import type { AgentBuilderSession, TranscriptTurn } from "./types";

export interface RenderExtras {
  proposedName?:  string | null;
  proposedSlug?:  string | null;
  verticalTag?:   string | null;   // e.g. "vertical:hvac"
  capabilityTag?: string | null;   // e.g. "capability:reporting"
}

export interface RenderedPRD {
  title:      string;
  body:       string;
  tags:       string[];
}

const NOT_SPECIFIED = "_(not specified — see transcript)_";

export function renderPRD(session: AgentBuilderSession, extras: RenderExtras = {}): RenderedPRD {
  const answers = extractAnswers(session.transcript);

  const name = extras.proposedName ?? session.proposed_name ?? "Unnamed Agent";
  const slug = extras.proposedSlug ?? session.proposed_slug ?? slugify(name);

  const title = `Agent: ${name}`;

  const tags: string[] = ["agent-request"];
  const vTag = extras.verticalTag   ?? session.vertical_tag;
  const cTag = extras.capabilityTag ?? session.capability_tag;
  if (vTag) tags.push(vTag);
  if (cTag) tags.push(cTag);

  const body = [
    `## Proposed Agent: ${name}   \`(id: ${slug})\``,
    ``,
    `**Requested by:** ${session.created_by ?? "unknown"}  `,
    `**Source:** ${session.source}  `,
    `**Captured:** ${session.created_at}  `,
    `**Session:** ${session.id}`,
    ``,
    `---`,
    ``,
    `### 1. Problem & current workaround`,
    answerOrNotSpecified(answers, 1),
    ``,
    `### 2. Trigger`,
    answerOrNotSpecified(answers, 2),
    ``,
    `### 3. Workflow stages (the dev's build list)`,
    answerOrNotSpecified(answers, 3),
    ``,
    `### 4. Input & output contract`,
    answerOrNotSpecified(answers, 4),
    ``,
    `### 5. Decision gates & exception handling`,
    answerOrNotSpecified(answers, 5),
    ``,
    `### 6. Voice, tone, format, guardrails & success metrics`,
    answerOrNotSpecified(answers, 6),
    ``,
    `### 7. Attachments`,
    renderAttachments(session),
    ``,
    `### 8. Suggested \`instance.md\` (scaffold starting point)`,
    "```yaml",
    `id: ${slug}`,
    `name: ${name}`,
    `baseWorkflow: custom   # engineering: set to reporting | blog | intake | data-import | custom`,
    `enabled: false         # start disabled until reviewed`,
    `brand:`,
    `  voice:    "(extract from §6)"`,
    `  tone:     "(extract from §6)"`,
    `  audience: "(extract from §1)"`,
    `  industry: "${vTag?.replace(/^vertical:/, "") ?? "(extract from §1)"}"`,
    `notify:`,
    `  approver:     "(from §5 if any)"`,
    `  slackChannel: "(from §4 if slack output)"`,
    `schedule:`,
    `  enabled: false       # engineering: true if cron trigger from §2`,
    `  cron:    ""           # e.g. "0 8 * * 1" Mon 8am (see §2)`,
    `  timezone: "America/Los_Angeles"`,
    `# Integration configs — engineering to populate per-vertical`,
    "```",
    ``,
    `### 9. Full transcript`,
    `<details>`,
    `<summary>Expand to see the Q&A session (${session.transcript.length} turns)</summary>`,
    ``,
    renderTranscript(session.transcript),
    ``,
    `</details>`,
    ``,
    `---`,
    `_Generated by Agent Builder • ${new Date().toISOString()}_`,
  ].join("\n");

  return { title, body, tags };
}

// ─── Extraction helpers ─────────────────────────────────────────────────────

interface ExtractedAnswer {
  questionIndex: number;
  question:      string;
  answer:        string;        // user's combined answer (collapsed from multiple user turns at this index if any)
  followUps:     string[];      // assistant turns at this index that came AFTER the first user answer (i.e. adaptive follow-ups)
}

function extractAnswers(transcript: TranscriptTurn[]): Map<number, ExtractedAnswer> {
  const out = new Map<number, ExtractedAnswer>();
  for (let i = 1; i <= CANONICAL_COUNT; i++) {
    const q = getCanonicalQuestion(i);
    if (!q) continue;

    const turnsForThisQ = transcript.filter((t) => t.question_index === i);
    const userTurns     = turnsForThisQ.filter((t) => t.role === "user");
    const assistantTurns = turnsForThisQ.filter((t) => t.role === "assistant");

    const answer = userTurns.map((t) => t.content).join("\n\n").trim();
    // Follow-ups are assistant turns OTHER than the initial canonical question.
    // (The initial canonical question is recorded with question_index = i too,
    // but it's the first assistant turn of that group.)
    const followUps = assistantTurns.slice(1).map((t) => t.content);

    out.set(i, {
      questionIndex: i,
      question:      q.canonical,
      answer,
      followUps,
    });
  }
  return out;
}

function answerOrNotSpecified(answers: Map<number, ExtractedAnswer>, index: number): string {
  const a = answers.get(index);
  if (!a || !a.answer) return NOT_SPECIFIED;

  // Indent the answer as a blockquote so it's visually distinct from section header.
  const quoted = a.answer
    .split("\n")
    .map((line) => (line.length === 0 ? ">" : `> ${line}`))
    .join("\n");

  if (a.followUps.length === 0) return quoted;

  // If there were adaptive follow-ups, include them inline after the primary answer.
  return [
    quoted,
    ``,
    `**Adaptive follow-ups asked:**`,
    ...a.followUps.map((f) => `- ${f}`),
  ].join("\n");
}

function renderAttachments(session: AgentBuilderSession): string {
  if (session.attachments.length === 0) return `_No attachments._`;
  return session.attachments
    .map((a) => `- [${a.filename}](${a.url}) (${a.mime_type}, ${prettyBytes(a.size_bytes)})`)
    .join("\n");
}

function renderTranscript(transcript: TranscriptTurn[]): string {
  return transcript
    .map((t) => {
      const header = t.role === "assistant" ? "**Elevarus**" : "**User**";
      const qTag   = t.question_index ? ` _(Q${t.question_index})_` : "";
      return `${header}${qTag}: ${t.content}`;
    })
    .join("\n\n");
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function prettyBytes(n: number): string {
  if (n <= 0) return "unknown size";
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}
